<?php

$_params = array(
	"einzelplan_namen" => array(
		"1998" => array(
    		"1" => "Landtag",
		    "2" => "Ministerpräsident und Staatskanzlei",
		    "3" => "Innenministerium",
		    "4" => "Justizministerium",
		    "5" => "Ministerium für Schule und Weiterbildung",
		    "6" => "Ministerium für Wissenschaft und Forschung",
		    "7" => "Ministerium für Arbeit, Gesundheit und Soziales",
		    "8" => "Ministerium für Wirtschaft und Mittelstand, Technologie und Verkehr",
		    "9" => "Ministerium für Bundes- und Europaangelegenheiten",
		    "10" => "Ministerium für Umwelt, Raumordnung und Landwirtschaft",
		    "11" => "Ministerium für die Gleichstellung von Frau und Mann",
		    "12" => "Finanzminsterium",
		    "13" => "Landesrechnungshof",
		    "14" => "Ministerium für Bauen und Wohnen",
		    "15" => "Ministerium für Stadtentwicklung, Kultur und Sport",
		    "20" => "Allgemeine Finanzverwaltung"
		),
		"1999" => array(
    		"1" => "Landtag",
		    "2" => "Ministerpräsident",
		    "3" => "Ministerium für Inneres und Justiz",
		    "4" => "",
		    "5" => "Ministerium für Schule und Weiterbildung",
		    "6" => "",
		    "7" => "",
		    "8" => "Ministerium für Wirtschaft, Mittelstand und Energie",
		    "9" => "",
		    "10" => "Ministerium für Umwelt und Naturschutz, Landwirtschaft und Verbraucherschutz",
		    "11" => "Ministerium für Arbeit, Gesundheit und Soziales",
		    "12" => "Finanzminsterium",
		    "13" => "Landesrechnungshof",
		    "14" => "Ministerium für Bauen und Verkehr",
		    "15" => "Ministerium für Generationen, Familie, Frauen und Integration",
		    "20" => "Allgemeine Finanzverwaltung"
		),
		"2000" => array(
    		"1" => "Landtag",
		    "2" => "Ministerpräsident",
		    "3" => "Innenministerium",
		    "4" => "Justizministerium",
		    "5" => "Ministerium für Schule und Weiterbildung",
		    "6" => "",
		    "7" => "",
		    "8" => "Ministerium für Wirtschaft, Mittelstand und Energie",
		    "9" => "",
		    "10" => "Ministerium für Umwelt und Naturschutz, Landwirtschaft und Verbraucherschutz",
		    "11" => "Ministerium für Arbeit, Gesundheit und Soziales",
		    "12" => "Finanzminsterium",
		    "13" => "Landesrechnungshof",
		    "14" => "Ministerium für Bauen und Verkehr",
		    "15" => "Ministerium für Generationen, Familie, Frauen und Integration",
		    "20" => "Allgemeine Finanzverwaltung"
		),
		"2001" => array(
    		"1" => "Landtag",
		    "2" => "Ministerpräsident",
		    "3" => "Innenministerium",
		    "4" => "Justizministerium",
		    "5" => "Ministerium für Schule und Weiterbildung",
		    "6" => "",
		    "7" => "",
		    "8" => "Ministerium für Wirtschaft, Mittelstand und Energie",
		    "9" => "",
		    "10" => "Ministerium für Umwelt und Naturschutz, Landwirtschaft und Verbraucherschutz",
		    "11" => "Ministerium für Arbeit, Gesundheit und Soziales",
		    "12" => "Finanzminsterium",
		    "13" => "Landesrechnungshof",
		    "14" => "Ministerium für Bauen und Verkehr",
		    "15" => "Ministerium für Generationen, Familie, Frauen und Integration",
		    "20" => "Allgemeine Finanzverwaltung"
		),
		"2002" => array(
    		"1" => "Landtag",
		    "2" => "Ministerpräsident",
		    "3" => "Innenministerium",
		    "4" => "Justizministerium",
		    "5" => "Ministerium für Schule und Weiterbildung",
		    "6" => "",
		    "7" => "",
		    "8" => "Ministerium für Wirtschaft, Mittelstand und Energie",
		    "9" => "",
		    "10" => "Ministerium für Umwelt und Naturschutz, Landwirtschaft und Verbraucherschutz",
		    "11" => "Ministerium für Arbeit, Gesundheit und Soziales",
		    "12" => "Finanzminsterium",
		    "13" => "Landesrechnungshof",
		    "14" => "Ministerium für Bauen und Verkehr",
		    "15" => "Ministerium für Generationen, Familie, Frauen und Integration",
		    "20" => "Allgemeine Finanzverwaltung"
		),
		"2003" => array(
    		"1" => "Landtag",
		    "2" => "Ministerpräsident",
		    "3" => "Innenministerium",
		    "4" => "Justizministerium",
		    "5" => "Ministerium für Schule und Weiterbildung",
		    "6" => "Ministerium für Innovation, Wissenschaft, Forschung und Technologie",
		    "7" => "",
		    "8" => "Ministerium für Wirtschaft, Mittelstand und Energie",
		    "9" => "",
		    "10" => "Ministerium für Umwelt und Naturschutz, Landwirtschaft und Verbraucherschutz",
		    "11" => "Ministerium für Arbeit, Gesundheit und Soziales",
		    "12" => "Finanzministerium",
		    "13" => "Landesrechnungshof",
		    "14" => "Ministerium für Bauen und Verkehr",
		    "15" => "Ministerium für Generationen, Familie, Frauen und Integration",
		    "20" => "Allgemeine Finanzverwaltung"
		),
		"2004" => array(
    		"1" => "Landtag",
		    "2" => "Ministerpräsident",
		    "3" => "Innenministerium",
		    "4" => "Justizministerium",
		    "5" => "Ministerium für Schule und Weiterbildung",
		    "6" => "Ministerium für Innovation, Wissenschaft, Forschung und Technologie",
		    "7" => "",
		    "8" => "Ministerium für Wirtschaft, Mittelstand und Energie",
		    "9" => "",
		    "10" => "Ministerium für Umwelt und Naturschutz, Landwirtschaft und Verbraucherschutz",
		    "11" => "Ministerium für Arbeit, Gesundheit und Soziales",
		    "12" => "Finanzministerium",
		    "13" => "Landesrechnungshof",
		    "14" => "Ministerium für Bauen und Verkehr",
		    "15" => "Ministerium für Generationen, Familie, Frauen und Integration",
		    "20" => "Allgemeine Finanzverwaltung"
		),
		"2006" => array(
    		"1" => "Landtag",
		    "2" => "Ministerpräsident",
		    "3" => "Innenministerium",
		    "4" => "Justizministerium",
		    "5" => "Ministerium für Schule und Weiterbildung",
		    "6" => "Ministerium für Innovation, Wissenschaft, Forschung und Technologie",
		    "7" => "",
		    "8" => "Ministerium für Wirtschaft, Mittelstand und Energie",
		    "9" => "",
		    "10" => "Ministerium für Umwelt und Naturschutz, Landwirtschaft und Verbraucherschutz",
		    "11" => "Ministerium für Arbeit, Gesundheit und Soziales",
		    "12" => "Finanzministerium",
		    "13" => "Landesrechnungshof",
		    "14" => "Ministerium für Bauen und Verkehr",
		    "15" => "Ministerium für Generationen, Familie, Frauen und Integration",
		    "20" => "Allgemeine Finanzverwaltung"
		),
		"2007" => array(
    		"1" => "Landtag",
		    "2" => "Ministerpräsident",
		    "3" => "Innenministerium",
		    "4" => "Justizministerium",
		    "5" => "Ministerium für Schule und Weiterbildung",
		    "6" => "Ministerium für Innovation, Wissenschaft, Forschung und Technologie",
		    "7" => "",
		    "8" => "Ministerium für Wirtschaft, Mittelstand und Energie",
		    "9" => "",
		    "10" => "Ministerium für Umwelt und Naturschutz, Landwirtschaft und Verbraucherschutz",
		    "11" => "Ministerium für Arbeit, Gesundheit und Soziales",
		    "12" => "Finanzministerium",
		    "13" => "Landesrechnungshof",
		    "14" => "Ministerium für Bauen und Verkehr",
		    "15" => "Ministerium für Generationen, Familie, Frauen und Integration",
		    "20" => "Allgemeine Finanzverwaltung"
		),
		"2008" => array(
    		"1" => "Landtag",
		    "2" => "Ministerpräsident",
		    "3" => "Innenministerium",
		    "4" => "Justizministerium",
		    "5" => "Ministerium für Schule und Weiterbildung",
		    "6" => "Ministerium für Innovation, Wissenschaft, Forschung und Technologie",
		    "7" => "",
		    "8" => "Ministerium für Wirtschaft, Mittelstand und Energie",
		    "9" => "",
		    "10" => "Ministerium für Umwelt und Naturschutz, Landwirtschaft und Verbraucherschutz",
		    "11" => "Ministerium für Arbeit, Gesundheit und Soziales",
		    "12" => "Finanzministerium",
		    "13" => "Landesrechnungshof",
		    "14" => "Ministerium für Bauen und Verkehr",
		    "15" => "Ministerium für Generationen, Familie, Frauen und Integration",
		    "20" => "Allgemeine Finanzverwaltung"
		),
		"2009" => array(
    		"1" => "Landtag",
		    "2" => "Ministerpräsident",
		    "3" => "Innenministerium",
		    "4" => "Justizministerium",
		    "5" => "Ministerium für Schule und Weiterbildung",
		    "6" => "Ministerium für Innovation, Wissenschaft, Forschung und Technologie",
		    "7" => "",
		    "8" => "Ministerium für Wirtschaft, Mittelstand und Energie",
		    "9" => "",
		    "10" => "Ministerium für Umwelt und Naturschutz, Landwirtschaft und Verbraucherschutz",
		    "11" => "Ministerium für Arbeit, Gesundheit und Soziales",
		    "12" => "Finanzministerium",
		    "13" => "Landesrechnungshof",
		    "14" => "Ministerium für Bauen und Verkehr",
		    "15" => "Ministerium für Generationen, Familie, Frauen und Integration",
		    "20" => "Allgemeine Finanzverwaltung"
		),
		"2010" => array(
    		"1" => "Landtag",
		    "2" => "Ministerpräsident",
		    "3" => "Innenministerium",
		    "4" => "Justizministerium",
		    "5" => "Ministerium für Schule und Weiterbildung",
		    "6" => "Ministerium für Innovation, Wissenschaft, Forschung und Technologie",
		    "7" => "",
		    "8" => "Ministerium für Wirtschaft, Mittelstand und Energie",
		    "9" => "",
		    "10" => "Ministerium für Umwelt und Naturschutz, Landwirtschaft und Verbraucherschutz",
		    "11" => "Ministerium für Arbeit, Gesundheit und Soziales",
		    "12" => "Finanzministerium",
		    "13" => "Landesrechnungshof",
		    "14" => "Ministerium für Bauen und Verkehr",
		    "15" => "Ministerium für Generationen, Familie, Frauen und Integration",
		    "20" => "Allgemeine Finanzverwaltung"
		),
		"2011" => array(
    		"1" => "Landtag",
		    "2" => "Ministerpräsidentin",
		    "3" => "Ministerium für Inneres und Kommunales",
		    "4" => "Justizministerium",
		    "5" => "Ministerium für Schule und Weiterbildung",
		    "6" => "Ministerium für Innovation, Wissenschaft und Forschung",
		    "7" => "Ministerium für Familie, Kinder, Jugend, Kultur und Sport",
		    "8" => "",
		    "9" => "",
		    "10" => "Ministerium für Klimaschutz, Umwelt, Landwirtschaft, Natur- und Verbraucherschutz",
		    "11" => "Ministerium für Arbeit, Integration und Soziales",
		    "12" => "Finanzministerium",
		    "13" => "Landesrechnungshof",
		    "14" => "Ministerium für Wirtschaft, Energie, Bauen, Wohnen und Verkehr",
		    "15" => "Ministerium für Gesundheit, Emanzipation, Pflege und Alter",
		    "20" => "Allgemeine Finanzverwaltung"
		),
		"2012" => array(
    		"1" => "Landtag",
		    "2" => "Ministerpräsidentin",
		    "3" => "Ministerium für Inneres und Kommunales",
		    "4" => "Justizministerium",
		    "5" => "Ministerium für Schule und Weiterbildung",
		    "6" => "Ministerium für Innovation, Wissenschaft und Forschung",
		    "7" => "Ministerium für Familie, Kinder, Jugend, Kultur und Sport",
		    "8" => "",
		    "9" => "Ministeriums für Bauen, Wohnen, Stadtentwicklung und Verkehr",
		    "10" => "Ministerium für Klimaschutz, Umwelt, Landwirtschaft, Natur- und Verbraucherschutz",
		    "11" => "Ministerium für Arbeit, Integration und Soziales",
		    "12" => "Finanzministerium",
		    "13" => "Landesrechnungshof",
		    "14" => "Ministerium für Wirtschaft, Energie, Industrie, Mittelstand und Handwerk",
		    "15" => "Ministerium für Gesundheit, Emanzipation, Pflege und Alter",
		    "20" => "Allgemeine Finanzverwaltung"
		),
		"2013" => array(
    		"1" => "Landtag",
		    "2" => "Ministerpräsidentin",
		    "3" => "Ministerium für Inneres und Kommunales",
		    "4" => "Justizministerium",
		    "5" => "Ministerium für Schule und Weiterbildung",
		    "6" => "Ministerium für Innovation, Wissenschaft und Forschung",
		    "7" => "Ministerium für Familie, Kinder, Jugend, Kultur und Sport",
		    "8" => "",
		    "9" => "Ministeriums für Bauen, Wohnen, Stadtentwicklung und Verkehr",
		    "10" => "Ministerium für Klimaschutz, Umwelt, Landwirtschaft, Natur- und Verbraucherschutz",
		    "11" => "Ministerium für Arbeit, Integration und Soziales",
		    "12" => "Finanzministerium",
		    "13" => "Landesrechnungshof",
		    "14" => "Wirtschaft, Energie, Industrie, Mittelstand und Handwerk",
		    "15" => "Ministerium für Gesundheit, Emanzipation, Pflege und Alter",
		    "20" => "Allgemeine Finanzverwaltung"
		),
		"2014" => array(
    		"1" => "Landtag",
		    "2" => "Ministerpräsidentin",
		    "3" => "Ministerium für Inneres und Kommunales",
		    "4" => "Justizministerium",
		    "5" => "Ministerium für Schule und Weiterbildung",
		    "6" => "Ministerium für Innovation, Wissenschaft und Forschung",
		    "7" => "Ministerium für Familie, Kinder, Jugend, Kultur und Sport",
		    "8" => "",
		    "9" => "Ministeriums für Bauen, Wohnen, Stadtentwicklung und Verkehr",
		    "10" => "Ministerium für Klimaschutz, Umwelt, Landwirtschaft, Natur- und Verbraucherschutz",
		    "11" => "Ministerium für Arbeit, Integration und Soziales",
		    "12" => "Finanzministerium",
		    "13" => "Landesrechnungshof",
		    "14" => "Wirtschaft, Energie, Industrie, Mittelstand und Handwerk",
		    "15" => "Ministerium für Gesundheit, Emanzipation, Pflege und Alter",
		    "20" => "Allgemeine Finanzverwaltung"
		),
		"2015" => array(
    		"1" => "Landtag",
		    "2" => "Ministerpräsidentin",
		    "3" => "Ministerium für Inneres und Kommunales",
		    "4" => "Justizministerium",
		    "5" => "Ministerium für Schule und Weiterbildung",
		    "6" => "Ministerium für Innovation, Wissenschaft und Forschung",
		    "7" => "Ministerium für Familie, Kinder, Jugend, Kultur und Sport",
		    "8" => "",
		    "9" => "Ministeriums für Bauen, Wohnen, Stadtentwicklung und Verkehr",
		    "10" => "Ministerium für Klimaschutz, Umwelt, Landwirtschaft, Natur- und Verbraucherschutz",
		    "11" => "Ministerium für Arbeit, Integration und Soziales",
		    "12" => "Finanzministerium",
		    "13" => "Landesrechnungshof",
		    "14" => "Wirtschaft, Energie, Industrie, Mittelstand und Handwerk",
		    "15" => "Ministerium für Gesundheit, Emanzipation, Pflege und Alter",
		    "20" => "Allgemeine Finanzverwaltung"
		)
	),
	"eoa_typen" => array(
		"Einnahmen" => "Einnahmen",
		"Ausgaben" => "Ausgaben",
	),
	"jahre" => array(
		"2015" => "2015",
		"2014" => "2014",
    	"2013" => "2013",
	    "2012" => "2012",
	    "2011" => "2011",
	    "2010" => "2010",
	    "2009" => "2009",
	    //"2009_1" => "2009 1. Nachtrag",
	    //"2009_2" => "2009 2. Nachtrag",
	    "2008" => "2008",
	    //"2008_1" => "2008 1. Nachtrag",
	    //"2008_2" => "2008 2. Nachtrag",
	    "2007" => "2007",
	    //"2007_1" => "2007 1. Nachtrag",
	    "2006" => "2006",
	    //"2006_1" => "2006 1. Nachtrag",
	    //"2005_1" => "2005 1. Nachtrag",
	    //"2004_2" => "2004 2. Nachtrag",
	    //"2004_1" => "2004 1. Nachtrag",
	    "2004" => "2004 / 2005",
	    "2003" => "2003",
	    //"2003_1" => "2003 1. Nachtrag",
	    "2002" => "2002",
	    "2001" => "2001",
	    "2000" => "2000",
	    //"2000_1" => "2000 1. Nachtrag",
	    "1999" => "1999",
   	 	"1998" => "1998",
	),
    "jahre_val" => array(
    	"1998",
	    "1999",
	    "2000",
	    "2001",
	    "2002",
	    "2003",
	    "2004 / 2005",
	    "2006",
	    "2007",
	    "2008",
	    "2009",
	    "2010",
	    "2011",
	    "2012",
	    "2013",
	    "2014",
        "2015"
    ),
	"einzelplan_farben" => array(
        "1" => "#481b79",
        "2" => "#f0c79c",
        "3" => "#ca221d",
        "4" => "#c22769",
        "5" => "#3f93e1",
        "6" => "#e29826",
        "7" => "#d32645",
        "8" => "#42928f",
        "9" => "#7a2077",
        "10" => "#edc92d",
        "11" => "#44913d",
        "12" => "#211d79",
        "13" => "#a5b425",
        "14" => "#2458a3",
        "15" => "#14388c",
        "20" => "#cd531c"
	),

	"dm_years" => array(
		"1998" => "1998",
		"1999" => "1999",
		"2000" => "2000",
		"2001" => "2001",
	),

	"factor_euro_dm" => 0.51,
);

include("custom.php");
$_params["einzelplan_namen"]["2003_1"] = $_params["einzelplan_namen"]["2003"];
$_params["einzelplan_namen"]["2000_1"] = $_params["einzelplan_namen"]["2000"];
return $_params;

?>
